# language: python
# python:
# - 3.5
osx_image: xcode8.1

os: osx

env:
  - SYNERGY_TAG=master


before_install:
- brew list --versions
- brew update
- brew outdated xctool || brew upgrade xctool


install:
- brew install python3
# - sudo ln -s /usr/local/bin/python3 /usr/bin/python3
- brew install cmake
- brew install qt
# - brew install openssh
# - brew install tree
- python3 download.py $SYNERGY_TAG
- mkdir build
- cd build
- cmake -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_OSX_ARCHITECTURES=x86_64 ../synergy-core
- make
# - tree
- ls -lha bin


script:
- pwd
- ls -lha .

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
#   file: "FILE TO UPLOAD"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

